title: RCmags
author: random-internet-guy
email: memoryofatrufestival@gmail.com
description: blog n' stuff

# index pagination
plugins:
- jekyll-paginate

paginate: 6
paginate_path: "/page:num/"

# collections
collections_dir: collections

collections:
  projects:
    output: true
  blog:
    output: true
    
# social links
github_username: RCmags
youtube_username: XXXmags
rcgroups_username_id: "189488"

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %b, %Y"

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# Order menu
#header_pages:
#  - projects.md
#  - about.md
