title: RCmags
author: Mags
email: memoryofatrufestival@gmail.com
description: Projects and other things

# index pagination
plugins:
- jekyll-paginate

paginate: 6
paginate_path: "/page:num/"

# collections
collections_dir: collections

# NOTE: listing MUST be updated with new pages
collections:
  projects:
    output: true
  blog:
    output: true
  travel:
    output: true
    
# social links
github_username: RCmags
youtube_username: XXXmags
rcgroups_username_id: "189488"

# toggled
google_analytics: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %b, %Y"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate

# Order menu
header_pages:
  - home.html
  - about.html
  - travel.html
  - blog.html
  - projects.html
  - search.html
